<?xml version="1.0"?>
<robot name="sensor_asus_xtion_pro" xmlns:xacro="http://ros.org/wiki/xacro"
                                    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
                                    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
                                    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor">
  <include filename="$(find turtlebot_description)/urdf/common_properties.urdf.xacro"/>
  
  <xacro:macro name="mount" params="parent">
  
  <joint name="pole_joint" type="fixed">
		<origin xyz="-0.038 0 0.073" rpy="0 0 0"/>
		<parent link="${parent}"/>
		<child link="pole" />
	</joint>
	
	<joint name="pole2_joint" type="fixed">
		<origin xyz="0.05 0 ${pole2_height + 0.01}" rpy="0 0 0"/>
		<parent link="pole"/>
		<child link="pole2" />
	</joint>
	
	<joint name="odroid_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="pole"/>
		<child link="odroid" />
	</joint>
	
	<joint name="servo_mount_joint" type="fixed">
		<origin xyz="0 -0.02 0.32" rpy="0 0 0"/>
		<parent link="pole2"/>
		<child link="servo" />
	</joint>
	
	<joint name="servo_joint" type="revolute">
		<axis xyz="0 1 0"/>
		<limit lower="${-M_PI/4}" upper="${M_PI/4}" effort="10" velocity="10"/>
		<origin xyz="0 0.0035 0.325" rpy="0 0 0"/>
		<parent link="pole2"/>
		<child link="servo_holder" />
	</joint>

	<link name="pole">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.08 0.24 0.02" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
		
		<visual>
			<origin xyz="0.03 0 0.18" rpy="0 0 0" />
			<geometry>
				<box size="0.02 0.02 0.34" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
		
		<visual>
			<origin xyz="0 0 0.10" rpy="0 0.3 0" />
			<geometry>
				<box size="0.02 0.02 0.20" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
		
		<collision>
			<origin xyz="0 0 -0.01" rpy="0 0 0" />
			<geometry>
				<cylinder length="0.56" radius="0.016495"/>
			</geometry>
		</collision>
			
	</link>
	
	
	<link name="pole2">
		<visual>
			<origin xyz="0 0 0.15" rpy="0 0 0" />
			<geometry>
				<box size="0.02 0.02 0.30" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
		<visual>
			<origin xyz="0 -0.0065 0.32" rpy="0 0 0" />
			<geometry>
				<box size="0.02 0.007 0.04" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
		
	</link>
	
	<link name="odroid">
		<visual>
			<origin xyz="0.01 -0.06 0.04" rpy="0 0 0" />
			<geometry>
				<box size="0.06 0.06 0.06" />
			</geometry>
			<material name="board_black">
				<color rgba="0.1 0.1 0.1 1"/>
			</material>
		</visual>
	</link>
	
	<link name="servo">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.01 0.03 0.03" />
			</geometry>
			<material name="board_black">
				<color rgba="0.2 0.2 0.2 1"/>
			</material>
		</visual>
		<visual>
			<origin xyz="0 0.02 0.005" rpy="${M_PI/2} 0 0" />
			<geometry>
				<cylinder radius="0.0025" length = "0.01"/>
			</geometry>
			<material name="board_black">
				<color rgba="0.2 0.2 0.2 1"/>
			</material>
		</visual>
	</link>	
	
	<link name="servo_holder">
		<visual>
			<origin xyz="0 0 0.012" rpy="0 0 0" />
			<geometry>
				<box size="0.02 0.003 0.04" />
			</geometry>
			<material name="Grey">
				<color rgba="0.6 0.6 0.6 1"/>
			</material>
		</visual>
	</link>
  
  </xacro:macro>
</robot>
